/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Foo */

#ifndef _Included_Foo
#define _Included_Foo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Foo
 * Method:    foo1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Foo_foo1
  (JNIEnv *, jclass);

/*
 * Class:     Foo
 * Method:    read
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_Foo_read
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
